from . import grok, replicate

PROVIDERS = {
    "grok": {
        "name": "Grok",
        "group": "xAI",
        "key_id": "xai",
        "pricing": "$0.05/sec at 480p; $0.07/sec at 720p",
        "cost_per_second_usd_by_resolution": {"480p": 0.05, "720p": 0.07},
        "cost_per_input_image_usd": 0.002,
        "models": ["grok-imagine-video"],
        "module": grok,
    },
    "hailuo": {
        "name": "Hailuo 2.3",
        "group": "MiniMax",
        "key_id": "replicate",
        "pricing": "$0.28/6s or $0.56/10s at 768p; $0.49/6s at 1080p",
        "cost_per_gen_usd_by_resolution": {"768p": {6: 0.28, 10: 0.56}, "1080p": {6: 0.49}},
        "models": ["minimax/hailuo-2.3"],
        "module": replicate,
    },
    "wan-t2v": {
        "name": "Text-to-Video (2.2 14B)",
        "group": "Wan",
        "key_id": "replicate",
        "pricing": "$0.05 at 480p; $0.10 at 720p",
        "cost_per_gen_usd_by_resolution": {"480p": 0.05, "720p": 0.10},
        "models": ["wan-video/wan-2.2-t2v-fast"],
        "module": replicate,
    },
    "wan-i2v": {
        "name": "Image-to-Video (2.2 14B)",
        "group": "Wan",
        "key_id": "replicate",
        "pricing": "$0.40 at 480p; $1.00 at 720p",
        "cost_per_gen_usd_by_resolution": {"480p": 0.40, "720p": 1.00},
        "models": ["wan-video/wan-2.2-i2v-a14b"],
        "module": replicate,
    },
    "wan-i2v-fast": {
        "name": "Image-to-Video Fast (2.2 14B)",
        "group": "Wan",
        "key_id": "replicate",
        "pricing": "$0.05–$0.065 at 480p; $0.11–$0.145 at 720p",
        "cost_per_gen_usd_by_resolution": {"480p": {"base": 0.05, "interpolate": 0.065}, "720p": {"base": 0.11, "interpolate": 0.145}},
        "models": ["wan-video/wan-2.2-i2v-fast"],
        "module": replicate,
    },
    "flux-image": {
        "name": "FLUX.2 Pro Still",
        "group": "Black Forest Labs",
        "key_id": "replicate",
        "pricing": "$0.03/1MP still; $0.045/2MP still",
        "cost_per_run_usd": 0.015,
        "cost_per_output_megapixel_usd": 0.015,
        "models": ["black-forest-labs/flux-2-pro"],
        "module": replicate,
        "output_kind": "image",
    },
    "pruna-pvideo": {
        "name": "P-Video",
        "group": "PrunaAI",
        "key_id": "replicate",
        "pricing": "$0.02/sec at 720p; $0.04/sec at 1080p → 5 crops per run",
        "cost_per_second_usd_by_resolution": {"720p": 0.02, "1080p": 0.04},
        "models": ["prunaai/p-video"],
        "module": replicate,
        "variant": "landscape",
    },
    "pruna-pvideo-vertical": {
        "name": "P-Video Vertical",
        "group": "PrunaAI",
        "key_id": "replicate",
        "pricing": "$0.02/sec at 720p; $0.04/sec at 1080p",
        "cost_per_second_usd_by_resolution": {"720p": 0.02, "1080p": 0.04},
        "models": ["prunaai/p-video"],
        "module": replicate,
        "variant": "vertical",
    },
}
